#!/usr/bin/env bash
# -*- sh -*-
set -o nounset
set -e

cd ebin
rm -f *.beam
erl -make
cd ..
erl -pa ebin \
    -kernel error_logger "{file,\"../install_errors.log\"}" \
    -sname extremeforge_installer \
    -noinput \
    -run extremeforge run || { echo "Installation failed."; exit 1; }
echo "Installation successfull."

